# Config File - BetterThings - By Ask Gaming(Amonly)
# If you need help, please contact me on Discord: 

#Thirst max: 200 - Fatigue max: 250 - The decrease task is per minute
#If you disble constant_action_bar, the plugin will send a message every time the player changues the value of thirst or fatigue
#If you disable_action_bar, the plugin will not send any action bar to the player
#Decay percentage of the lemon item, 0.1 = 10% of decay - #Apple has 0.05 of decay
constant_action_bar: true
disable_action_bar: false

thirst: 
  emoji: üç∂
  decrease: 4 
  amount_on_fire_blocks: true
  damage_when_0: 1
  deny_actions:
    regain_health_below: 25
    nausea_on_place_blocks_below: 50
  enable_worlds:
  - world
  - world_nether
     
fatigue: 
  emoji: üõå
  decrease: 2 
  rest_inday_increase: 50
  force_sleep_in_day: true
  hunger_after_sleep: true
  damage_when_0: 1
  deny_actions:
    regain_health_below: 25
    cancel_sprint_below: 50
    minig_fatigue_below: 70
  enable_worlds:
  - world
  - world_the_end

others:
  enable_recipes: true
  lemon_item_name: "&aLemon"
  chance_decay_drop: 0.1

drink_from_water_block: #Drink from water block
  enable: true
  value: 10 #10 thirst value
  chance_to_get_sick: 30 #30%
