# Config File - BetterThings - By Ask Gaming(Amonly)
# If you need help, please contact me on Discord: 

constant_action_bar: true

thirst: # Max 200
  enable: true
  emoji: ğŸ¶
  decrease: 4 # How much thirst will be decreased per minute
  amount_on_fire_blocks: true
  hurt_when_0: true
  deny_actions:
    nausea_on_place_blocks_below: 50
  deny_actions:
    
  enable_worlds:
  - world
  - world_nether
     
fatigue: # Max 250
  enable: true
  emoji: ğŸ›Œ
  decrease: 2 # How much fatigue will be decreased per minute
  rest_inday_increase: 50
  force_sleep_in_day: true
  hunger_after_sleep: true
  hurt_when_0: true
  deny_actions:
    regain_health_below: 25
    cancel_sprint_below: 50
    minig_fatigue_below: 70
  enable_worlds:
  - world
  - world_the_end

